package com.concise.pos.domain;
// Generated Oct 25, 2016 4:03:07 PM by Hibernate Tools 5.1.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "concise_pos")
public class Product implements java.io.Serializable {

	private Integer productId;
	private Category category;
	private Store store;
	private String name;
	private double price;
	private int quantity;
	private List<SellLine> sellLines;

	public Product() {
	}

	public Product(Category category, Store store, String name, double price, int quantity) {
		this.category = category;
		this.store = store;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
	}

	public Product(Category category, Store store, String name, double price, int quantity, List<SellLine> sellLines) {
		this.category = category;
		this.store = store;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
		this.sellLines = sellLines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "productId", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryId", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "storeId", nullable = false)
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public List<SellLine> getSellLines() {
		return this.sellLines;
	}

	public void setSellLines(List<SellLine> sellLines) {
		this.sellLines = sellLines;
	}

}
