package com.concise.pos.domain;

/**
 * SellLine generated by hbm2java
 */
public class SellLine implements java.io.Serializable {

	private Integer sellLineId;
	private Product product;
	private Sell sell;
	private String name;
	private double price;

	public SellLine() {
	}

	public SellLine(Product product, Sell sell, String name, double price) {
		this.product = product;
		this.sell = sell;
		this.name = name;
		this.price = price;
	}

	public Integer getSellLineId() {
		return this.sellLineId;
	}

	public void setSellLineId(Integer sellLineId) {
		this.sellLineId = sellLineId;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Sell getSell() {
		return this.sell;
	}

	public void setSell(Sell sell) {
		this.sell = sell;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
