package com.concise.pos.domain;
// Generated Oct 14, 2016 2:40:26 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Sell generated by hbm2java
 */
public class Sell implements java.io.Serializable {

	private Integer sellId;
	private User user;
	private Date date;
	private List<SellLine> sellLines;

	public Sell() {
	}

	public Sell(User user, Date date) {
		this.user = user;
		this.date = date;
	}

	public Sell(User user, Date date, List<SellLine> sellLines) {
		this.user = user;
		this.date = date;
		this.sellLines = sellLines;
	}

	public Integer getSellId() {
		return this.sellId;
	}

	public void setSellId(Integer sellId) {
		this.sellId = sellId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public List<SellLine> getSellLines() {
		return this.sellLines;
	}

	public void setSellLines(List<SellLine> sellLines) {
		this.sellLines = sellLines;
	}

}
