package com.concise.pos.domain;
// Generated Oct 25, 2016 3:25:52 PM by Hibernate Tools 5.1.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SellLine generated by hbm2java
 */
@Entity
@Table(name = "sell_line", catalog = "concise_pos")
public class SellLine implements java.io.Serializable {

	private Integer sellLineId;
	private Product product;
	private Sell sell;
	private String name;
	private double price;

	public SellLine() {
	}

	public SellLine(Product product, Sell sell, String name, double price) {
		this.product = product;
		this.sell = sell;
		this.name = name;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sellLineId", unique = true, nullable = false)
	public Integer getSellLineId() {
		return this.sellLineId;
	}

	public void setSellLineId(Integer sellLineId) {
		this.sellLineId = sellLineId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sellId", nullable = false)
	public Sell getSell() {
		return this.sell;
	}

	public void setSell(Sell sell) {
		this.sell = sell;
	}

	@Column(name = "name", nullable = false, length = 500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
