package com.concise.domain;
// Generated Oct 14, 2016 2:40:26 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store implements java.io.Serializable {

	private Integer storeId;
	private String name;
	private int phone;
	private List<Product> products;

	public Store() {
	}

	public Store(String name, int phone) {
		this.name = name;
		this.phone = phone;
	}

	public Store(String name, int phone, List<Product> products) {
		this.name = name;
		this.phone = phone;
		this.products = products;
	}

	public Integer getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getPhone() {
		return this.phone;
	}

	public void setPhone(int phone) {
		this.phone = phone;
	}

	public List<Product> getProducts() {
		return this.products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}

}
