package com.concise.domain;
// Generated Oct 14, 2016 2:40:26 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer productId;
	private Category category;
	private Store store;
	private int name;
	private double price;
	private int quantity;
	private List<SellLine> sellLines;

	public Product() {
	}

	public Product(Category category, Store store, int name, double price, int quantity) {
		this.category = category;
		this.store = store;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
	}

	public Product(Category category, Store store, int name, double price, int quantity, List<SellLine> sellLines) {
		this.category = category;
		this.store = store;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
		this.sellLines = sellLines;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public int getName() {
		return this.name;
	}

	public void setName(int name) {
		this.name = name;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public List<SellLine> getSellLines() {
		return this.sellLines;
	}

	public void setSellLines(List<SellLine> sellLines) {
		this.sellLines = sellLines;
	}

}
